import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext(null);

const translations = {
  en: {
    "logo.resolve": "Resolve",
    "nav.features": "Features",
    "nav.howItWorks": "How It Works",
    "nav.categories": "Categories",
    "nav.submitComplaint": "Submit Complaint",
    "nav.signIn": "Sign In",
    "nav.register": "Register",
    "nav.dashboard": "Dashboard",
    "nav.signOut": "Sign Out",
    
    "hero.badge": "Smart Civic Management",
    "hero.title1": "Resolve Civic Grievances",
    "hero.title2": "Transparently & Swiftly",
    "hero.subtitle": "Report infrastructure issues, sanitation, water leakage, or lighting problems and watch them get assigned, tracked, and resolved by local authorities in real-time.",
    "hero.submitBtn": "Submit a Complaint",
    "hero.createAccount": "Create Citizen Account",
    "hero.trackLabel": "Fast Tracker System",
    "hero.trackPlaceholder": "Enter Complaint Number (e.g. 1)",
    "hero.trackBtn": "Track Status",

    "stats.resolved": "Resolved Complaints",
    "stats.active": "Active Issues",
    "stats.avgTime": "Average Resolution Time",
    "stats.satisfaction": "Resolution Rate",

    "footer.tagline": "CivicResolve is a Cloud-enabled municipal portal built to bridge the gap between citizens, administrators, and field workers to build smarter, cleaner cities.",
    "footer.quickLinks": "Quick Links",
    "footer.portals": "Municipal Portals",
    "footer.citizenPortal": "Citizen Portal",
    "footer.adminDashboard": "Admin Control Panel",
    "footer.workerPortal": "Worker Workspace",
    "footer.contact": "Contact Support",
    "footer.copyright": "© 2026 CivicResolve. All rights reserved.",
    "footer.credit": "Developed for Cloud Computing & Web Projects.",

    "login.title": "Welcome Back",
    "login.subtitle": "Log in to your portal using credentials",
    "login.username": "Username",
    "login.password": "Password",
    "login.btn": "Sign In",
    "login.noAccount": "Don't have an account?",
    "login.signupLink": "Sign up here",

    "register.title": "Register Citizen Account",
    "register.subtitle": "Sign up to submit and track local community complaints",
    "register.fullName": "Full Name",
    "register.email": "Email Address",
    "register.phone": "Mobile Number",
    "register.address": "Residential Address",
    "register.confirmPassword": "Confirm Password",
    "register.btn": "Register Account",
    "register.hasAccount": "Already registered?",
    "register.loginLink": "Log in here",

    "complaint.pageTitle": "Submit Civic Grievance",
    "complaint.pageSubtitle": "Please provide accurate details about the local issue to help us dispatch workers correctly.",
    "complaint.detailsTitle": "Complaint Details",
    "complaint.detailsSubtitle": "Tell us what is wrong and select a category and priority level",
    "complaint.title": "Complaint Title",
    "complaint.titlePlaceholder": "e.g. Potholes on Main Street near Metro Station",
    "complaint.category": "Category",
    "complaint.categoryPlaceholder": "Select a category",
    "complaint.priority": "Priority Level",
    "complaint.priorityPlaceholder": "Select priority",
    "complaint.description": "Detailed Description",
    "complaint.descriptionPlaceholder": "Describe the issue, landmarks, and duration of the problem...",
    "complaint.attachments": "Attachments & Pictures",
    "complaint.uploadText": "Drag and drop or click here to upload photo",
    "complaint.uploadHint": "Only JPG, PNG, GIF, and WEBP formats (Max 10MB)",
    "complaint.locationTitle": "Incident Location",
    "complaint.locationSubtitle": "Specify where the problem is located",
    "complaint.location": "Street Address",
    "complaint.locationPlaceholder": "e.g. Block 4B, Sector 62, Landmark Park",
    "complaint.coords": "Coordinates (Optional)",
    "complaint.latitude": "Latitude",
    "complaint.longitude": "Longitude",
    "complaint.contactTitle": "Contact Information Verification",
    "complaint.contactSubtitle": "These details will be used for follow-ups and notifications",
    "complaint.cancel": "Cancel",
    "complaint.submit": "Submit Complaint",
    "complaint.success": "Grievance submitted successfully!",

    "dashboard.citizen": "Citizen Workspace",
    "dashboard.admin": "Admin Control Dashboard",
    "dashboard.worker": "Worker Tasks Workspace",
    "dashboard.allComplaints": "Grievance Records",
    "dashboard.newWorker": "Add New Worker",
    "dashboard.workers": "Workers",
    "dashboard.citizens": "Citizens",

    "cat.form.roads": "Roads & Potholes",
    "cat.form.water": "Water Leakage & Supply",
    "cat.form.electricity": "Electricity Failure",
    "cat.form.sanitation": "Sanitation & Waste",
    "cat.form.safety": "Public Safety",
    "cat.form.parks": "Parks & Recreation",
    "cat.form.building": "Illegal Building & Construction",
    "cat.form.drainage": "Drainage & Sewage Leakage",
    "cat.form.lighting": "Streetlight Failure",
    "cat.form.noise": "Noise Pollution",
    "cat.form.other": "Other Grievances",
  },
  hi: {
    "logo.resolve": "निवारण",
    "nav.features": "विशेषताएं",
    "nav.howItWorks": "यह कैसे काम करता है",
    "nav.categories": "श्रेणियां",
    "nav.submitComplaint": "शिकायत दर्ज करें",
    "nav.signIn": "लॉग इन करें",
    "nav.register": "रजिस्टर करें",
    "nav.dashboard": "डैशबोर्ड",
    "nav.signOut": "लॉग आउट",

    "hero.badge": "स्मार्ट नागरिक प्रबंधन",
    "hero.title1": "नागरिक समस्याओं का",
    "hero.title2": "पारदर्शी और त्वरित निवारण",
    "hero.subtitle": "सड़क के गड्ढे, स्वच्छता, पानी का रिसाव, या बिजली की समस्याओं की रिपोर्ट करें और वास्तविक समय में स्थानीय अधिकारियों द्वारा उन्हें सौंपे, ट्रैक और हल होते देखें।",
    "hero.submitBtn": "शिकायत दर्ज करें",
    "hero.createAccount": "नागरिक खाता बनाएं",
    "hero.trackLabel": "फास्ट ट्रैकर सिस्टम",
    "hero.trackPlaceholder": "शिकायत संख्या दर्ज करें (जैसे 1)",
    "hero.trackBtn": "ट्रैक करें",

    "stats.resolved": "निवारण की गई शिकायतें",
    "stats.active": "सक्रिय समस्याएं",
    "stats.avgTime": "औसत निवारण समय",
    "stats.satisfaction": "सफलता दर",

    "footer.tagline": "CivicResolve एक क्लाउड-सक्षम नागरिक पोर्टल है जिसे नागरिकों, प्रशासकों और क्षेत्रीय कार्यकर्ताओं के बीच की दूरी को पाटने के लिए बनाया गया है।",
    "footer.quickLinks": "त्वरित लिंक्स",
    "footer.portals": "नगरपालिका पोर्टल",
    "footer.citizenPortal": "नागरिक पोर्टल",
    "footer.adminDashboard": "प्रशासक नियंत्रण डैशबोर्ड",
    "footer.workerPortal": "कार्यकर्ता कार्यक्षेत्र",
    "footer.contact": "सहायता से संपर्क करें",
    "footer.copyright": "© 2026 CivicResolve. सभी अधिकार सुरक्षित।",
    "footer.credit": "क्लाउड कंप्यूटिंग और वेब प्रोजेक्ट के लिए विकसित।",

    "login.title": "स्वागत हे",
    "login.subtitle": "क्रेडेंशियल्स का उपयोग करके अपने पोर्टल में लॉग इन करें",
    "login.username": "उपयोगकर्ता नाम",
    "login.password": "पासवर्ड",
    "login.btn": "लॉग इन करें",
    "login.noAccount": "खाता नहीं है?",
    "login.signupLink": "यहाँ रजिस्टर करें",

    "register.title": "नागरिक खाता पंजीकृत करें",
    "register.subtitle": "स्थानीय समुदाय की शिकायतें दर्ज करने और ट्रैक करने के लिए साइन अप करें",
    "register.fullName": "पूरा नाम",
    "register.email": "ईमेल पता",
    "register.phone": "मोबाइल नंबर",
    "register.address": "आवासीय पता",
    "register.confirmPassword": "पासवर्ड की पुष्टि करें",
    "register.btn": "खाता पंजीकृत करें",
    "register.hasAccount": "पहले से पंजीकृत हैं?",
    "register.loginLink": "यहाँ लॉग इन करें",

    "complaint.pageTitle": "नागरिक शिकायत दर्ज करें",
    "complaint.pageSubtitle": "कार्यकर्ताओं को सही ढंग से भेजने में हमारी मदद करने के लिए स्थानीय समस्या के बारे में सटीक विवरण प्रदान करें।",
    "complaint.detailsTitle": "शिकायत का विवरण",
    "complaint.detailsSubtitle": "हमें बताएं कि क्या गलत है और श्रेणी और प्राथमिकता स्तर चुनें",
    "complaint.title": "शिकायत का शीर्षक",
    "complaint.titlePlaceholder": "उदा. मेट्रो स्टेशन के पास मेन स्ट्रीट पर गड्ढे",
    "complaint.category": "श्रेणी",
    "complaint.categoryPlaceholder": "एक श्रेणी चुनें",
    "complaint.priority": "प्राथमिकता स्तर",
    "complaint.priorityPlaceholder": "प्राथमिकता चुनें",
    "complaint.description": "विस्तृत विवरण",
    "complaint.descriptionPlaceholder": "समस्या, स्थलों और समस्या की अवधि का वर्णन करें...",
    "complaint.attachments": "अनुलग्नक और चित्र",
    "complaint.uploadText": "फ़ोटो अपलोड करने के लिए खींचें और छोड़ें या यहाँ क्लिक करें",
    "complaint.uploadHint": "केवल JPG, PNG, GIF और WEBP प्रारूप (अधिकतम 10MB)",
    "complaint.locationTitle": "घटना स्थल",
    "complaint.locationSubtitle": "निर्दिष्ट करें कि समस्या कहाँ स्थित है",
    "complaint.location": "सड़क का पता",
    "complaint.locationPlaceholder": "उदा. ब्लॉक 4B, सेक्टर 62, लैंडमार्क पार्क",
    "complaint.coords": "निर्देशांक (वैकल्पिक)",
    "complaint.latitude": "अक्षांश",
    "complaint.longitude": "देशांतर",
    "complaint.contactTitle": "संपर्क जानकारी का सत्यापन",
    "complaint.contactSubtitle": "इन विवरणों का उपयोग फॉलो-अप और सूचनाओं के लिए किया जाएगा",
    "complaint.cancel": "रद्द करें",
    "complaint.submit": "शिकायत दर्ज करें",
    "complaint.success": "शिकायत सफलतापूर्वक दर्ज की गई!",

    "dashboard.citizen": "नागरिक कार्यक्षेत्र",
    "dashboard.admin": "प्रशासक नियंत्रण डैशबोर्ड",
    "dashboard.worker": "कार्यकर्ता कार्यक्षेत्र",
    "dashboard.allComplaints": "शिकायत रिकॉर्ड",
    "dashboard.newWorker": "नया कार्यकर्ता जोड़ें",
    "dashboard.workers": "कार्यकर्ता",
    "dashboard.citizens": "नागरिक",

    "cat.form.roads": "सड़कें और गड्ढे",
    "cat.form.water": "पानी का रिसाव और आपूर्ति",
    "cat.form.electricity": "बिजली की समस्या",
    "cat.form.sanitation": "स्वच्छता और कचरा",
    "cat.form.safety": "सार्वजनिक सुरक्षा",
    "cat.form.parks": "पार्क और मनोरंजन",
    "cat.form.building": "अवैध निर्माण",
    "cat.form.drainage": "जल निकासी और सीवेज रिसाव",
    "cat.form.lighting": "स्ट्रीटलाइट विफलता",
    "cat.form.noise": "ध्वनि प्रदूषण",
    "cat.form.other": "अन्य शिकायतें",
  },
  bn: {
    "logo.resolve": "সমাধান",
    "nav.features": "বৈশিষ্ট্য",
    "nav.howItWorks": "কার্যপ্রণালী",
    "nav.categories": "বিভাগসমূহ",
    "nav.submitComplaint": "অভিযোগ জমা দিন",
    "nav.signIn": "লগ ইন",
    "nav.register": "নিবন্ধন",
    "nav.dashboard": "ড্যাশবোর্ড",
    "nav.signOut": "লগ আউট",
    
    "hero.badge": "স্মার্ট নাগরিক ব্যবস্থাপনা",
    "hero.title1": "নাগরিক সমস্যার",
    "hero.title2": "স্বচ্ছ ও দ্রুত সমাধান",
    "hero.subtitle": "রাস্তার গর্ত, জল নিষ্কাশন, বিদ্যুৎ বিভ্রাট বা পরিচ্ছন্নতার মতো সমস্যা অবিলম্বে রিপোর্ট করুন এবং রিয়েল-টাইমে সেটির সমাধান দেখুন।",
    "hero.submitBtn": "অভিযোগ জমা দিন",
    "hero.createAccount": "নাগরিক অ্যাকাউন্ট তৈরি করুন",
    "hero.trackLabel": "দ্রুত ট্র্যাকার সিস্টেম",
    "hero.trackPlaceholder": "অভিযোগ নম্বর লিখুন (যেমন ১)",
    "hero.trackBtn": "ট্র্যাক করুন",

    "stats.resolved": "সমাধান করা অভিযোগ",
    "stats.active": "সক্রিয় সমস্যা",
    "stats.avgTime": "গড় সমাধান সময়",
    "stats.satisfaction": "সমাধানের হার",

    "footer.tagline": "CivicResolve হল একটি ক্লাউড-সক্ষম পৌর পোর্টাল যা নাগরিক, প্রশাসক এবং কর্মীদের মধ্যে দূরত্ব দূর করতে সাহায্য করে।",
    "footer.quickLinks": "দ্রুত লিঙ্ক",
    "footer.portals": "পৌর পোর্টাল",
    "footer.citizenPortal": "নাগরিক পোর্টাল",
    "footer.adminDashboard": "প্রশাসক ড্যাশবোর্ড",
    "footer.workerPortal": "কর্মী পোর্টাল",
    "footer.copyright": "© ২০২৬ CivicResolve. সর্বস্বত্ব সংরক্ষিত।",
    "footer.credit": "ক্লাউড কম্পিউটিং ও ওয়েব প্রজেক্টের জন্য নির্মিত।",

    "login.title": "স্বাগতম",
    "login.subtitle": "ক্যাডেন্সিয়াল ব্যবহার করে আপনার পোর্টালে লগ ইন করুন",
    "login.username": "ব্যবহারকারীর নাম",
    "login.password": "পাসওয়ার্ড",
    "login.btn": "লগ ইন করুন",
    "login.noAccount": "অ্যাকাউন্ট নেই?",
    "login.signupLink": "এখানে নিবন্ধন করুন",

    "register.title": "নাগরিক নিবন্ধন",
    "register.subtitle": "অভিযোগ জমা দিতে এবং ট্র্যাক করতে সাইন আপ করুন",
    "register.fullName": "সম্পূর্ণ নাম",
    "register.email": "ইমেল ঠিকানা",
    "register.phone": "মোবাইল নম্বর",
    "register.address": "আবাসিক ঠিকানা",
    "register.confirmPassword": "পাসওয়ার্ড নিশ্চিত করুন",
    "register.btn": "অ্যাকাউন্ট নিবন্ধন করুন",
    "register.hasAccount": "ইতিমধ্যেই অ্যাকাউন্ট আছে?",
    "register.loginLink": "এখানে লগ ইন করুন",

    "complaint.pageTitle": "নাগরিক অভিযোগ জমা দিন",
    "complaint.pageSubtitle": "অনুগ্রহ করে সঠিক বিবরণ প্রদান করুন যাতে আমরা দ্রুত সমাধান করতে পারি।",
    "complaint.detailsTitle": "অভিযোগের বিবরণ",
    "complaint.detailsSubtitle": "সমস্যাটি কি এবং এর বিভাগ ও অগ্রাধিকার সিলেক্ট করুন",
    "complaint.title": "অভিযোগের শিরোনাম",
    "complaint.titlePlaceholder": "যেমন: প্রধান রাস্তার উপর বড় গর্ত",
    "complaint.category": "বিভাগ",
    "complaint.categoryPlaceholder": "বিভাগ নির্বাচন করুন",
    "complaint.priority": "অফিসিয়াল অগ্রাধিকার",
    "complaint.priorityPlaceholder": "অগ্রাধিকার নির্বাচন করুন",
    "complaint.description": "বিস্তারিত বর্ণনা",
    "complaint.descriptionPlaceholder": "ল্যান্ডমার্ক এবং সমস্যার সময়কাল সহ বিস্তারিত বিবরণ লিখুন...",
    "complaint.attachments": "সংযুক্ত ছবি",
    "complaint.uploadText": "ফাইলটি এখানে টেনে আনুন বা আপলোড করতে ক্লিক করুন",
    "complaint.uploadHint": "শুধুমাত্র JPG, PNG, GIF, WEBP ফরম্যাট (সর্বোচ্চ ১০MB)",
    "complaint.locationTitle": "ঘটনার স্থান",
    "complaint.locationSubtitle": "সমস্যাটি কোথায় অবস্থিত তা নির্দিষ্ট করুন",
    "complaint.location": "রাস্তার ঠিকানা",
    "complaint.locationPlaceholder": "যেমন: সেক্টর ৬২, নোইডা",
    "complaint.coords": "স্থানাঙ্ক (ঐচ্ছিক)",
    "complaint.latitude": "অক্ষাংশ",
    "complaint.longitude": "দ্রাঘিমাংশ",
    "complaint.contactTitle": "যোগাযোগের তথ্য যাচাইকরণ",
    "complaint.contactSubtitle": "যোগাযোগের জন্য এই তথ্য ব্যবহার করা হবে",
    "complaint.cancel": "বাতিল",
    "complaint.submit": "অভিযোগ জমা দিন",
    "complaint.success": "অভিযোগ সফলভাবে জমা দেওয়া হয়েছে!",

    "dashboard.citizen": "নাগরিক কার্যক্ষেত্র",
    "dashboard.admin": "প্রশাসনিক নিয়ন্ত্রণ ড্যাশবোর্ড",
    "dashboard.worker": "কর্মী কার্যক্ষেত্র",
    "dashboard.allComplaints": "অভিযোগ রেকর্ড",
    "dashboard.newWorker": "নতুন কর্মী যোগ করুন",
    "dashboard.workers": "কর্মীগণ",
    "dashboard.citizens": "নাগরিকগণ",

    "cat.form.roads": "রাস্তা ও গর্ত",
    "cat.form.water": "জল সরবরাহ ও লিক",
    "cat.form.electricity": "বিদ্যুৎ বিভ্রাট",
    "cat.form.sanitation": "পরিচ্ছন্নতা ও বর্জ্য",
    "cat.form.safety": "জননিরাপত্তা",
    "cat.form.parks": "পার্ক ও বিনোদন",
    "cat.form.building": "অবৈধ নির্মাণ",
    "cat.form.drainage": "নর্দমা উপচে পড়া",
    "cat.form.lighting": "রাস্তার আলো বিভ্রাট",
    "cat.form.noise": "শব্দ দূষণ",
    "cat.form.other": "অন্যান্য অভিযোগ"
  },
  te: {
    "logo.resolve": "పరిష్కారం",
    "nav.features": "ఫీచర్లు",
    "nav.howItWorks": "ఇది ఎలా పనిచేస్తుంది",
    "nav.categories": "విభాగాలు",
    "nav.submitComplaint": "ఫిర్యాదు సమర్పించండి",
    "nav.signIn": "లాగిన్",
    "nav.register": "నమోదు",
    "nav.dashboard": "డ్యాష్‌బోర్డ్",
    "nav.signOut": "లాగ్ అవుట్",
    
    "hero.badge": "స్మార్ట్ సివిక్ మేనేజ్‌మెంట్",
    "hero.title1": "పౌర సమస్యల",
    "hero.title2": "పారదర్శక & వేగవంతమైన పరిష్కారం",
    "hero.subtitle": "రోడ్డు గుంతలు, డ్రైనేజీ లీకేజీలు, నీటి వృధా లేదా వీధి దీపాల సమస్యలను నివేదించండి మరియు వాటి పరిష్కారాన్ని నిజ సమయంలో ట్రాక్ చేయండి.",
    "hero.submitBtn": "ఫిర్యాదు సమర్పించండి",
    "hero.createAccount": "పౌర ఖాతాను సృష్టించండి",
    "hero.trackLabel": "వేగవంతమైన ట్రాకర్ సిస్టమ్",
    "hero.trackPlaceholder": "ఫిర్యాదు సంఖ్యను నమోదు చేయండి (ఉదా. 1)",
    "hero.trackBtn": "ట్రాక్ చేయండి",

    "stats.resolved": "పరిష్కరించబడిన ఫిర్యాదులు",
    "stats.active": "క్రియాశీల సమస్యలు",
    "stats.avgTime": "సగటు పరిష్కార సమయం",
    "stats.satisfaction": "పరిష్కార రేటు",

    "footer.tagline": "CivicResolve అనేది పౌరులు, నిర్వాహకులు మరియు క్షేత్రస్థాయి సిబ్బంది మధ్య దూరాన్ని తగ్గించడానికి సృష్టించబడిన క్లౌడ్-ఆధారిత మునిసిపల్ పోర్టల్.",
    "footer.quickLinks": "శీఘ్ర లింకులు",
    "footer.portals": "మునిసిపల్ పోర్టల్స్",
    "footer.citizenPortal": "పౌర పోర్టల్",
    "footer.adminDashboard": "అడ్మిన్ నియంత్రణ ప్యానెల్",
    "footer.workerPortal": "వర్కర్ పోర్టల్",
    "footer.copyright": "© 2026 CivicResolve. అన్ని హక్కులూ ప్రత్యేకించుకోవడమైనది.",
    "footer.credit": "క్లౌడ్ కంప్యూటింగ్ & వెబ్ ప్రాజెక్ట్ కోసం అభివృద్ధి చేయబడింది.",

    "login.title": "తిరిగి స్వాగతం",
    "login.subtitle": "మీ ఆధారాలను ఉపయోగించి లాగిన్ అవ్వండి",
    "login.username": "వినియోగదారు పేరు",
    "login.password": "పాస్‌వర్డ్",
    "login.btn": "లాగిన్ అవ్వండి",
    "login.noAccount": "ఖాతా లేదా?",
    "login.signupLink": "ఇక్కడ నమోదు చేసుకోండి",

    "register.title": "పౌర ఖాతా నమోదు",
    "register.subtitle": "ఫిర్యాదులను సమర్పించడానికి మరియు ట్రాక్ చేయడానికి సైన్ అప్ చేయండి",
    "register.fullName": "పూర్తి పేరు",
    "register.email": "ఇమెయిల్ చిరునామా",
    "register.phone": "మొబైల్ సంఖ్య",
    "register.address": "నివాస చిరునామా",
    "register.confirmPassword": "పాస్‌వర్డ్ నిర్ధారించండి",
    "register.btn": "ఖాతాను నమోదు చేయండి",
    "register.hasAccount": "ఇప్పటికే నమోదయ్యారా?",
    "register.loginLink": "ఇక్కడ లాగిన్ అవ్వండి",

    "complaint.pageTitle": "పౌర ఫిర్యాదును సమర్పించండి",
    "complaint.pageSubtitle": "క్షేత్రస్థాయి సిబ్బందిని త్వరగా పంపడానికి దయచేసి సరైన వివరాలను అందించండి.",
    "complaint.detailsTitle": "ఫిర్యాదు వివరాలు",
    "complaint.detailsSubtitle": "సమస్య ఏమిటో తెలిపి, విభాగం మరియు ప్రాధాన్యతను ఎంచుకోండి",
    "complaint.title": "ఫిర్యాదు శీర్షిక",
    "complaint.titlePlaceholder": "ఉదా. మెయిన్ రోడ్డుపై పెద్ద గుంత",
    "complaint.category": "విభాగం",
    "complaint.categoryPlaceholder": "విభాగాన్ని ఎంచుకోండి",
    "complaint.priority": "ప్రాధాన్యత స్థాయి",
    "complaint.priorityPlaceholder": "ప్రాధాన్యతను ఎంచుకోండి",
    "complaint.description": "వివరణాత్మక వివరణ",
    "complaint.descriptionPlaceholder": "సమస్య, సమీప గుర్తులు మరియు సమస్య కాలవ్యవధిని వివరించండి...",
    "complaint.attachments": "జతచేయబడిన ఫోటోలు",
    "complaint.uploadText": "ఫోటోను ఇక్కడకు లాగండి లేదా అప్‌లోడ్ చేయడానికి క్లిక్ చేయండి",
    "complaint.uploadHint": "JPG, PNG, GIF, WEBP ఫార్మాట్లు మాత్రమే (గరిష్టంగా 10MB)",
    "complaint.locationTitle": "సమస్య ప్రాంతం",
    "complaint.locationSubtitle": "సమస్య ఎక్కడ ఉందో పేర్కొనండి",
    "complaint.location": "వీధి చిరునామా",
    "complaint.locationPlaceholder": "ఉదా. సెక్టార్ 62, నోయిడా",
    "complaint.coords": "కోఆర్డినేట్లు (ఐచ్ఛికం)",
    "complaint.latitude": "అక్షాంశం",
    "complaint.longitude": "రేఖాంశం",
    "complaint.contactTitle": "సంప్రదింపు సమాచార ధృవీకరణ",
    "complaint.contactSubtitle": "తదుపరి సంప్రదింపుల కోసం ఈ వివరాలు ఉపయోగించబడతాయి",
    "complaint.cancel": "రద్దు చేయి",
    "complaint.submit": "ఫిర్యాదు సమర్పించు",
    "complaint.success": "ఫిర్యాదు విజయవంతంగా సమర్పించబడింది!",

    "dashboard.citizen": "పౌర కార్యస్థలం",
    "dashboard.admin": "అడ్మిన్ నియంత్రణ ప్యానెల్",
    "dashboard.worker": "వర్కర్ కార్యస్థలం",
    "dashboard.allComplaints": "ఫిర్యాదు రికార్డులు",
    "dashboard.newWorker": "కొత్త వర్కర్‌ని జోడించండి",
    "dashboard.workers": "వర్కర్లు",
    "dashboard.citizens": "పౌరులు",

    "cat.form.roads": "రోడ్లు & గుంతలు",
    "cat.form.water": "నీటి లీకేజీ & సరఫరా",
    "cat.form.electricity": "విద్యుత్ సమస్యలు",
    "cat.form.sanitation": "శుభ్రత & వ్యర్థాలు",
    "cat.form.safety": "ప్రజా భద్రత",
    "cat.form.parks": "పార్కులు & వినోదం",
    "cat.form.building": "అక్రమ నిర్మాణాలు",
    "cat.form.drainage": "డ్రైనేజీ లీకేజీ",
    "cat.form.lighting": "వీధి దీపాల పతనం",
    "cat.form.noise": "శబ్ద కాలుష్యం",
    "cat.form.other": "ఇతర ఫిర్యాదులు"
  },
  ta: {
    "logo.resolve": "தீர்வு",
    "nav.features": "அம்சங்கள்",
    "nav.howItWorks": "எப்படி செயல்படுகிறது",
    "nav.categories": "பிரிவுகள்",
    "nav.submitComplaint": "புகார் சமர்ப்பிக்கவும்",
    "nav.signIn": "உள்நுழைக",
    "nav.register": "பதிவு செய்க",
    "nav.dashboard": "டாஷ்போர்டு",
    "nav.signOut": "வெளியேறுக",
    
    "hero.badge": "ஸ்மார்ட் குடிமை மேலாண்மை",
    "hero.title1": "குடிமை பிரச்சினைகளுக்கு",
    "hero.title2": "வெளிப்படையான & விரைவான தீர்வு",
    "hero.subtitle": "சாலைப் பள்ளங்கள், கழிவுநீர் கசிவு அல்லது தெருவிளக்கு பழுது போன்ற பிரச்சினைகளை புகாரளித்து, அவற்றின் தீர்வை உடனுக்குடன் கண்காணிக்கவும்.",
    "hero.submitBtn": "புகார் சமர்ப்பிக்கவும்",
    "hero.createAccount": "குடிமகன் கணக்கை உருவாக்கவும்",
    "hero.trackLabel": "விரைவான கண்காணிப்பு அமைப்பு",
    "hero.trackPlaceholder": "புகார் எண்ணை உள்ளிடவும் (எ.கா. 1)",
    "hero.trackBtn": "கண்காணிக்கவும்",

    "stats.resolved": "தீர்க்கப்பட்ட புகார்கள்",
    "stats.active": "செயலில் உள்ள பிரச்சினைகள்",
    "stats.avgTime": "சராசரி தீர்வு நேரம்",
    "stats.satisfaction": "தீர்வு விகிதம்",

    "footer.tagline": "CivicResolve என்பது குடிமக்கள், நிர்வாகிகள் மற்றும் ஊழியர்களுக்கு இடையிலான இடைவெளியைக் குறைக்க உருவாக்கப்பட்ட கிளவுட் முனிசிப்பல் போர்ட்டல் ஆகும்.",
    "footer.quickLinks": "விரைவு இணைப்புகள்",
    "footer.portals": "நகராட்சி போர்ட்டல்கள்",
    "footer.citizenPortal": "குடிமகன் போர்ட்டல்",
    "footer.adminDashboard": "நிர்வாகக் கட்டுப்பாட்டு வாரியம்",
    "footer.workerPortal": "ஊழியர் பணிமனை",
    "footer.copyright": "© 2026 CivicResolve. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
    "footer.credit": "கிளவுட் கம்ப்யூட்டிங் மற்றும் வலைத் திட்டத்திற்காக உருவாக்கப்பட்டது.",

    "login.title": "மீண்டும் வருக",
    "login.subtitle": "உங்கள் சான்றுகளைப் பயன்படுத்தி உள்நுழைக",
    "login.username": "பயனர் பெயர்",
    "login.password": "கடவுச்சொல்",
    "login.btn": "உள்நுழைக",
    "login.noAccount": "கணக்கு இல்லையா?",
    "login.signupLink": "இங்கே பதிவு செய்க",

    "register.title": "குடிமகன் பதிவு",
    "register.subtitle": "புகார்களைச் சமர்ப்பிக்கவும் கண்காணிக்கவும் பதிவு செய்யவும்",
    "register.fullName": "முழு பெயர்",
    "register.email": "மின்னஞ்சல் முகவரி",
    "register.phone": "கைபேசி எண்",
    "register.address": "வீட்டு முகவரி",
    "register.confirmPassword": "கடவுச்சொல்லை உறுதிப்படுத்துக",
    "register.btn": "கணக்கை பதிவு செய்க",
    "register.hasAccount": "ஏற்கனவே பதிவு செய்துள்ளீர்களா?",
    "register.loginLink": "இங்கே உள்நுழைக",

    "complaint.pageTitle": "குடிமை புகாரைச் சமர்ப்பிக்கவும்",
    "complaint.pageSubtitle": "ஊழியர்களை விரைவாக அனுப்ப தயவுசெய்து துல்லியமான விவரங்களை வழங்கவும்.",
    "complaint.detailsTitle": "புகார் விவரங்கள்",
    "complaint.detailsSubtitle": "பிரச்சினை என்னவென்று கூறி, பிரிவு மற்றும் முன்னுரிமையைத் தேர்ந்தெடுக்கவும்",
    "complaint.title": "புகார் தலைப்பு",
    "complaint.titlePlaceholder": "எ.கா. பிரதான சாலையில் பெரிய பள்ளம்",
    "complaint.category": "பிரிவு",
    "complaint.categoryPlaceholder": "பிரிவைத் தேர்ந்தெடுக்கவும்",
    "complaint.priority": "முன்னுரிமை நிலை",
    "complaint.priorityPlaceholder": "முன்னுரிமையைத் தேர்ந்தெடுக்கவும்",
    "complaint.description": "விரிவான விளக்கம்",
    "complaint.descriptionPlaceholder": "பிரச்சினை, அடையாளங்கள் மற்றும் கால அளவை விளக்கவும்...",
    "complaint.attachments": "இணைக்கப்பட்ட புகைப்படங்கள்",
    "complaint.uploadText": "புகைப்படத்தை இங்கே இழுக்கவும் அல்லது பதிவேற்ற கிளிக் செய்யவும்",
    "complaint.uploadHint": "JPG, PNG, GIF, WEBP வடிவங்கள் மட்டும் (அதிகபட்சம் 10MB)",
    "complaint.locationTitle": "பிரச்சினை பகுதி",
    "complaint.locationSubtitle": "பிரச்சினை எங்குள்ளது என்பதைக் குறிப்பிடவும்",
    "complaint.location": "தெரு முகவரி",
    "complaint.locationPlaceholder": "எ.கா. செக்டர் 62, நொய்டா",
    "complaint.coords": "ஒருங்கிணைப்புகள் (விரும்பினால்)",
    "complaint.latitude": "அட்சரேகை",
    "complaint.longitude": "தீர்க்கரேகை",
    "complaint.contactTitle": "தொடர்புத் தகவல் சரிபார்ப்பு",
    "complaint.contactSubtitle": "அடுத்தகட்டத் தொடர்புகளுக்கு இந்த விவரங்கள் பயன்படுத்தப்படும்",
    "complaint.cancel": "ரத்து செய்க",
    "complaint.submit": "புகாரைச் சமர்ப்பி",
    "complaint.success": "புகார் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது!",

    "dashboard.citizen": "குடிமகன் போர்ட்டல்",
    "dashboard.admin": "நிர்வாகக் கட்டுப்பாட்டு வாரியம்",
    "dashboard.worker": "ஊழியர் பணிமனை",
    "dashboard.allComplaints": "புகார் பதிவுகள்",
    "dashboard.newWorker": "புதிய ஊழியரைச் சேர்க்கவும்",
    "dashboard.workers": "ஊழியர்கள்",
    "dashboard.citizens": "குடிமக்கள்",

    "cat.form.roads": "சாலைகள் & பள்ளங்கள்",
    "cat.form.water": "நீர் கசிவு & விநியோகம்",
    "cat.form.electricity": "மின்சார பிரச்சினைகள்",
    "cat.form.sanitation": "சத்தம் & கழிவுகள்",
    "cat.form.safety": "பொதுப் பாதுகாப்பு",
    "cat.form.parks": "பூங்காக்கள் & பொழுதுபோக்கு",
    "cat.form.building": "அனுமதியற்ற கட்டுமானங்கள்",
    "cat.form.drainage": "கழிவுநீர் கசிவு",
    "cat.form.lighting": "தெருவிளக்கு பழுது",
    "cat.form.noise": "ஒலி மாசுபாடு",
    "cat.form.other": "இதர புகார்கள்"
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('civic_lang') || 'en');

  const changeLanguage = (newLang) => {
    setLang(newLang);
    localStorage.setItem('civic_lang', newLang);
  };

  const t = (key) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage: lang, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
