name: Build and deploy JAR app to Azure Web App - civic-complaint-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      # Checkout GitHub repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Java
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      # Build Spring Boot project from backend folder
      - name: Build with Maven
        run: |
          cd backend
          mvn clean install

      # Deploy JAR to Azure App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'civic-complaint-app'
          slot-name: 'Production'
          package: 'backend/target/*.jar'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FC4E1E7A769441FAA7E919EC5A2DCFEE }}
